### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by MilchRatchet** [jeremyong/flop#1]
I am using the alpha build. The program opens a window and immediately crashes afterwards. The only message that is printed to the console is:

> Using device: NVIDIA GeForce RTX 3070 Ti

I am running on Windows 10.

**Comment by MilchRatchet** [comment]
Nevermind it was a graphics driver error. So flop does not run on nvidia driver 496.76 but on 511.79

**Comment by jeremyong** [comment]
This is one "issue" with using a relatively recent extension (dynamic rendering). I used it mainly to take the new API for a test spin, but will mean that older drivers don't support the extension and it will crash.

If I have time, I should probably try to detect this scenario and handle it more gracefully (or just not use the dynamic rendering extension as it isn't strictly necessary for this project).

Thanks for reporting the issue!
