### ISSUE TITLE
Support EXR

### ISSUE THREAD

**Issue by samcake** [jeremyong/flop#2]
Hi Jeremy,

I love your app!
ANd would love it even more if we could use EXR file format :)
Thanks much for your contribution!

S

**Comment by jeremyong** [comment]
This is something I want also and should be pretty easy to add. Task for this weekend!

**Comment by jeremyong** [comment]
@samcake 
EXR support is in, feel free to give it a try here: https://github.com/jeremyong/flop/releases/tag/v1.618
