### ISSUE TITLE
Fairly significant difference in output compared to reference implementation

### ISSUE THREAD

**Issue by fu5ha** [jeremyong/flop#3]
Hi! I noticed there was a fairly significant difference in the output of flop and the reference impl provided by nvidia... see:

[flop ldr error map](https://github.com/jeremyong/flop/raw/main/test/flop.png)

vs.

[reference ldr error map](https://raw.githubusercontent.com/NVlabs/flip/main/tests/correct_ldrflip_python.png)

**Comment by jeremyong** [comment]
Hey! Sorry for the late response, are the input images HDR? One difference between FLIP and FLOP at the moment is that FLOP doesn’t have an autoexposure built-in to use in the HDR to LDR tonemapping process.

**Comment by jeremyong** [comment]
I'm going to close now as I assume the discrepancy is due to the lack of an "auto exposure" in FLOP compared to the original FLIP but feel free to reopen if there are other issues. I may implement the auto-exposure at a later time but don't have bandwidth at the moment.
